apiVersion: v1
kind: Secret
metadata:
  name: akita-secrets
type: Opaque
data:
  api-key-id: {{required "A base64 .Values.apiKeyId from the Akita console is required" .Values.apiKeyId}}
  api-key-secret: {{required "A base64 .Values.apiKeySecret from the Akita console is required" .Values.apiKeySecret}}

